# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.deleteRowButton = QtWidgets.QPushButton(Dialog)
        self.deleteRowButton.setObjectName("deleteRowButton")
        self.verticalLayout.addWidget(self.deleteRowButton)
        self.refreshButton = QtWidgets.QPushButton(Dialog)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout.addWidget(self.refreshButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "List"))
        self.addButton.setText(_translate("Dialog", "Add New"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.saveButton.setShortcut(_translate("Dialog", "Ctrl+S"))
        self.deleteRowButton.setText(_translate("Dialog", "Delete Row"))
        self.refreshButton.setText(_translate("Dialog", "Refresh"))
        self.refreshButton.setShortcut(_translate("Dialog", "F5"))
